image: golang:1.14.0

cache:
  paths:
    - .cache

stages:
  - test
  - build

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

unit_tests:
  stage: test
  script:
    - go test ./...

data_race_detector:
  stage: test
  script:
    - go test -race ./...

build:
  stage: build
  script:
    - go build ./...