image: golang:1.12.9

cache:
  paths:
    - .cache

stages:
  - test
  - build

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

lint:
  stage: test
  script:
    - go get -u golang.org/x/lint/golint
    - golint ./...

unit_tests:
  stage: test
  script:
    - go test ./...

data_race_detector:
  stage: test
  script:
    - go test -race ./...

build:
  stage: build
  script:
    - go build ./...