version: '3'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    hostname: redis
    networks:
      - redis-net
  
  redis-monitor:
    depends_on: 
      - redis
    image: redis
    container_name: redis-monitor
    hostname: redis-monitor
    networks:
      - redis-net
    entrypoint: redis-cli -h redis monitor

  redis-scan:
    depends_on: 
      - redis
      - redis-monitor
    image: redis
    container_name: redis-scan
    hostname: redis-scan
    networks:
      - redis-net
    command: 
      - /bin/sh
      - -c 
      - "while true; do redis-cli -h redis scan 0; sleep 10; done"

networks:
  redis-net: