name: Go build

on: [push]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: "1.21.5"
      - name: Unit tests
        run: |
          go test ./...
      - name: Race detector
        run: |
          go test -race ./...
      - name: Build
        run: |
          go build ./...
